#!/usr/bin/env python3
"""Generate src/ft8lib/_tables.py from the WSJT-X Fortran sources.

Parses:
  wsjtx/lib/ft8/ldpc_174_91_c_generator.f90  -> generator matrix rows (hex)
  wsjtx/lib/ft8/ldpc_174_91_c_parity.f90     -> Mn (174x3), Nm (83x7), nrw (83)

Run from the repository root:  python tools/gen_tables.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FT8 = ROOT / "wsjtx" / "lib" / "ft8"
OUT = ROOT / "src" / "ft8lib" / "_tables.py"


def parse_generator():
    text = (FT8 / "ldpc_174_91_c_generator.f90").read_text()
    rows = re.findall(r'"([0-9a-fA-F]{23})"', text)
    assert len(rows) == 83, f"expected 83 generator rows, got {len(rows)}"
    return rows


def parse_parity():
    text = (FT8 / "ldpc_174_91_c_parity.f90").read_text()
    # Strip Fortran continuation markers and comments
    text = text.replace("&", " ")

    def block(name):
        m = re.search(rf"data\s+{name}\s*/(.*?)/", text, re.S | re.I)
        assert m, f"table {name} not found"
        return [int(x) for x in re.findall(r"-?\d+", m.group(1))]

    mn = block("Mn")
    nm = block("Nm")
    nrw = block("nrw")
    assert len(mn) == 174 * 3, len(mn)
    assert len(nm) == 83 * 7, len(nm)
    assert len(nrw) == 83, len(nrw)
    Mn = [mn[i * 3:(i + 1) * 3] for i in range(174)]
    Nm = [nm[i * 7:(i + 1) * 7] for i in range(83)]
    return Mn, Nm, nrw


def main():
    gen = parse_generator()
    Mn, Nm, nrw = parse_parity()
    with OUT.open("w") as f:
        f.write('"""LDPC(174,91) tables extracted from WSJT-X Fortran sources.\n\n')
        f.write("Auto-generated by tools/gen_tables.py -- do not edit.\n")
        f.write('"""\n\n')
        f.write("# Generator matrix: 83 rows of 91 columns, packed as 23 hex chars per row\n")
        f.write("LDPC_GENERATOR_HEX = (\n")
        for row in gen:
            f.write(f'    "{row}",\n')
        f.write(")\n\n")
        f.write("# Mn[j] = the three parity checks (1-based) that involve codeword bit j+1\n")
        f.write("LDPC_MN = (\n")
        for row in Mn:
            f.write(f"    ({row[0]}, {row[1]}, {row[2]}),\n")
        f.write(")\n\n")
        f.write("# Nm[i] = the codeword bits (1-based, 0-padded) checked by parity row i+1\n")
        f.write("LDPC_NM = (\n")
        for row in Nm:
            f.write("    (" + ", ".join(str(x) for x in row) + "),\n")
        f.write(")\n\n")
        f.write("# Number of bits participating in each parity check\n")
        f.write("LDPC_NRW = (\n")
        for i in range(0, 83, 16):
            f.write("    " + ", ".join(str(x) for x in nrw[i:i + 16]) + ",\n")
        f.write(")\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
